<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Include="../PerfectArtwork/*.cs" Link="%(Filename)%(Extension)" />
    <Compile Include="../ApplicationIntegrations/ApplicationIntegrationDataStore.cs" Link="ApplicationIntegrationDataStore.cs" />
  </ItemGroup>
</Project>
