import { normalizeStoreLocale, type StoreLocale } from "./pluginStoreLocale";
type Tab = "audio" | "performance" | "graphics" | "controller" | "customize";
const text: Record<StoreLocale, readonly string[]> = {
  en: ["Your screen, adjusted", "Adjust brightness, resolution, refresh rate and HDR where supported.", "Your sound, adjusted", "Choose speakers and microphone, and adjust their volume.", "More from every frame", "Find Lossless Scaling and AMD graphics controls when available on your system.", "Controls that fit", "Select your controller and open its supported settings and Steam Input controls.", "Make Playhub yours", "Arrange or hide tabs, manage Playhub and Decky in Quick Access, and find device information and diagnostics."],
  it: ["Il video, come lo vuoi", "Regola luminosità, risoluzione, frequenza di aggiornamento e HDR dove supportati.", "Il suono, come lo vuoi", "Scegli uscita audio e microfono e regola i rispettivi volumi.", "Più controllo su ogni frame", "Trova i controlli di Lossless Scaling e della grafica AMD disponibili sul tuo sistema.", "I comandi, come li vuoi", "Seleziona il controller e apri le impostazioni supportate e i controlli di Steam Input.", "Playhub, come lo vuoi tu", "Riordina o nascondi le tab, gestisci Playhub e Decky nell'accesso rapido e consulta informazioni sul dispositivo e diagnostica."],
  es: ["La imagen a tu gusto", "Ajusta brillo, resolución, frecuencia de actualización y HDR cuando sea compatible.", "El sonido a tu gusto", "Elige la salida de audio y el micrófono y ajusta sus volúmenes.", "Más control en cada fotograma", "Encuentra los controles de Lossless Scaling y gráficos AMD disponibles en tu sistema.", "Controles a tu medida", "Selecciona tu mando y abre sus ajustes compatibles y los controles de Steam Input.", "Haz Playhub tuyo", "Ordena u oculta pestañas, gestiona Playhub y Decky en el acceso rápido y consulta información del dispositivo y diagnósticos."],
  fr: ["L’image à votre goût", "Réglez luminosité, résolution, fréquence de rafraîchissement et HDR si pris en charge.", "Le son à votre goût", "Choisissez la sortie audio et le microphone et réglez leurs volumes.", "Plus de contrôle sur chaque image", "Retrouvez les commandes Lossless Scaling et graphiques AMD disponibles sur votre système.", "Des commandes à votre mesure", "Sélectionnez votre manette et ouvrez ses réglages compatibles et les commandes Steam Input.", "Un Playhub à votre image", "Organisez ou masquez les onglets, gérez Playhub et Decky dans l’accès rapide et consultez les informations de l’appareil et les diagnostics."],
  de: ["Dein Bildschirm, angepasst", "Passe Helligkeit, Auflösung, Bildwiederholrate und unterstütztes HDR an.", "Dein Sound, angepasst", "Wähle Audioausgabe und Mikrofon und passe ihre Lautstärke an.", "Mehr Kontrolle über jedes Bild", "Finde die auf deinem System verfügbaren Einstellungen für Lossless Scaling und AMD-Grafik.", "Steuerung nach deinem Geschmack", "Wähle deinen Controller und öffne unterstützte Einstellungen sowie Steam Input.", "Mach Playhub zu deinem", "Ordne Tabs an oder blende sie aus, verwalte Playhub und Decky im Schnellzugriff und finde Geräteinformationen und Diagnosen."],
  pt: ["A imagem do seu jeito", "Ajuste brilho, resolução, taxa de atualização e HDR quando compatível.", "O som do seu jeito", "Escolha a saída de áudio e o microfone e ajuste seus volumes.", "Mais controle em cada quadro", "Encontre os controles de Lossless Scaling e gráficos AMD disponíveis no seu sistema.", "Controles do seu jeito", "Selecione seu controle e abra as configurações compatíveis e os controles do Steam Input.", "Deixe o Playhub com a sua cara", "Organize ou oculte abas, gerencie Playhub e Decky no acesso rápido e consulte informações do dispositivo e diagnósticos."],
  uk: ["Зображення на ваш смак", "Налаштовуйте яскравість, роздільність, частоту оновлення та HDR за наявності підтримки.", "Звук на ваш смак", "Вибирайте аудіовихід і мікрофон та налаштовуйте їхню гучність.", "Більше контролю над кадром", "Знаходьте доступні у вашій системі налаштування Lossless Scaling і графіки AMD.", "Зручне керування", "Виберіть контролер і відкрийте його підтримувані налаштування та Steam Input.", "Налаштуйте Playhub під себе", "Упорядковуйте або приховуйте вкладки, керуйте Playhub і Decky у швидкому доступі та переглядайте відомості про пристрій і діагностику."],
  zh: ["按喜好调整画面", "调整亮度、分辨率、刷新率及受支持的 HDR。", "按喜好调整声音", "选择音频输出和麦克风，并调整各自音量。", "掌控每一帧", "查找系统中可用的 Lossless Scaling 和 AMD 图形控制选项。", "适合你的操作", "选择控制器，打开其支持的设置和 Steam Input 控制选项。", "打造你的 Playhub", "排列或隐藏标签页，管理快捷访问中的 Playhub 和 Decky，并查看设备信息与诊断。"],
  ja: ["画面を自分好みに", "明るさ、解像度、リフレッシュレート、対応するHDRを調整できます。", "音を自分好みに", "音声出力とマイクを選び、それぞれの音量を調整できます。", "一枚一枚の映像を調整", "システムで利用できる Lossless Scaling と AMD グラフィックスの設定を確認できます。", "自分に合った操作へ", "コントローラーを選び、対応する設定や Steam Input を開けます。", "Playhub を自分らしく", "タブの並べ替えや非表示、クイックアクセスの Playhub・Decky の管理、デバイス情報や診断の確認ができます。"],
  ko: ["나에게 맞는 화면", "밝기, 해상도, 주사율 및 지원되는 HDR을 조정하세요.", "나에게 맞는 소리", "오디오 출력과 마이크를 선택하고 각각의 볼륨을 조정하세요.", "프레임마다 더 세밀하게", "시스템에서 사용할 수 있는 Lossless Scaling과 AMD 그래픽 설정을 찾아보세요.", "나에게 맞는 조작", "컨트롤러를 선택하고 지원되는 설정과 Steam Input을 여세요.", "나만의 Playhub로", "탭을 정렬하거나 숨기고, 빠른 액세스의 Playhub와 Decky를 관리하며, 기기 정보와 진단을 확인하세요."],
  hi: ["अपनी पसंद का वीडियो", "समर्थित चमक, रिज़ॉल्यूशन, रीफ़्रेश दर और HDR समायोजित करें।", "अपनी पसंद की आवाज़", "ऑडियो आउटपुट और माइक्रोफ़ोन चुनें और उनका वॉल्यूम समायोजित करें।", "हर फ़्रेम पर बेहतर नियंत्रण", "अपने सिस्टम पर उपलब्ध Lossless Scaling और AMD ग्राफ़िक्स नियंत्रण खोजें।", "आपके हिसाब से नियंत्रण", "अपना कंट्रोलर चुनें और उसकी समर्थित सेटिंग तथा Steam Input खोलें।", "Playhub को अपना बनाएँ", "टैब व्यवस्थित करें या छिपाएँ, त्वरित ऐक्सेस में Playhub और Decky प्रबंधित करें और उपकरण की जानकारी व निदान देखें।"],
  ru: ["Изображение по вашему вкусу", "Настраивайте яркость, разрешение, частоту обновления и HDR, если поддерживается.", "Звук по вашему вкусу", "Выбирайте аудиовыход и микрофон и настраивайте их громкость.", "Больше контроля над кадром", "Находите доступные в вашей системе настройки Lossless Scaling и графики AMD.", "Удобное управление", "Выберите контроллер и откройте его поддерживаемые настройки и Steam Input.", "Настройте Playhub под себя", "Упорядочивайте или скрывайте вкладки, управляйте Playhub и Decky в быстром доступе и просматривайте сведения об устройстве и диагностику."],
};
export function getOnboardingTabCopy(locale: unknown, tab: Tab) {
  const index = ["audio", "performance", "graphics", "controller", "customize"].indexOf(tab) * 2;
  const values = text[normalizeStoreLocale(locale)];
  return { title: values[index], body: values[index + 1] };
}
