<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>PluginLoader</AssemblyName>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../GamingModeAgent/GamingMode.Services/DeckyOrphanCleanup.cs" Link="DeckyOrphanCleanup.cs" />
  </ItemGroup>
</Project>
