#!/usr/bin/env python3
"""Derive tools/history-wanted.json from the day table and the catalog.

Every day names a subject and says where its picture can be found. This turns that
into the list the fetcher works through, adding nothing that is already on disk.
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DAYS = os.path.join(ROOT, 'quick_settings', 'history_days.json')
MANIFEST = os.path.join(ROOT, 'quick_settings', 'history_images.json')
WANTED = os.path.join(ROOT, 'tools', 'history-wanted.json')

MANUAL = [
    {"theme": "gta", "subject": "Grand Theft Auto 2", "kind": "screenshot",
     "file": "gta2-0.jpg", "provider": "remote",
     "ref": "https://www.igrandtheftauto.com/content/images/gta2-official-screenshot-4.jpg?etag=6745856e",
     "sourceUrl": "https://www.igrandtheftauto.com/gta2/images",
     "credit": "iGrandTheftAuto.com · official screenshot"},
    {"theme": "gta", "subject": "Grand Theft Auto: Chinatown Wars", "kind": "screenshot",
     "file": "chinatown-0.jpg", "provider": "remote",
     "ref": "https://www.igrandtheftauto.com/content/images/gta-chinatown-wars-wilhelm-2-5.webp?etag=690cc262",
     "sourceUrl": "https://www.igrandtheftauto.com/gtacw/images",
     "credit": "iGrandTheftAuto.com · official screenshot"},
    {"theme": "newyear", "subject": "Hanafuda cards", "kind": "object",
     "file": "newyear-hanafuda-1.jpg", "provider": "commons", "ref": "Hanafuda cards"},
    {"theme": "access", "subject": "Xbox Adaptive Controller in use", "kind": "photo",
     "file": "access-in-use.jpg", "provider": "commons", "ref": "Xbox Adaptive Controller"},
    # igdb.com/games/portal is a 1986 Activision game. The Steam app id is unambiguous.
    {"theme": "portal", "subject": "Portal", "kind": "screenshot",
     "file": "portal-valve-0.jpg", "provider": "steam", "ref": 400},
]


def main():
    with io.open(DAYS, encoding='utf-8-sig') as handle:
        days = json.load(handle)['days']
    with io.open(MANIFEST, encoding='utf-8-sig') as handle:
        manifest = json.load(handle)

    rows = list(MANUAL)
    for date in sorted(days):
        entry = days[date]
        media = entry.get('media')
        # A day that reuses an existing theme's pictures needs nothing downloaded.
        if not media or entry.get('media_id') in manifest:
            continue
        theme = f'day-{date}'
        rows.append({'theme': theme, 'subject': entry['subject'],
                     'kind': media.get('kind', 'cover'),
                     'file': f"day-{date}-0.{media.get('ext', 'jpg')}",
                     'provider': media['provider'], 'ref': media['ref']})

    have = {item.get('file') for entries in manifest.values() for item in entries}
    rows = [row for row in rows if row['file'] not in have]
    payload = {'_comment': 'Generated by tools/build-history-wanted.py from '
                           'quick_settings/history_days.json. Run tools/fetch-history-images.py '
                           '(or double-click the .bat) on a machine with internet access.',
               'wanted': rows}
    with io.open(WANTED, 'w', encoding='utf-8', newline='\n') as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=1)
        handle.write('\n')
    print(f'{WANTED}: {len(rows)} images still to fetch.')


if __name__ == '__main__':
    main()
