#!/usr/bin/env python3
"""Generate src/historyImages.ts from quick_settings/history_images.json.

The manifest is the single source of truth: this writes the bundler imports so a
file referenced by two themes is imported once, and the emitted order matches the
manifest so diffs stay readable.
"""
import json
import os
import argparse
import re
import hashlib
from urllib.parse import quote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, 'quick_settings', 'history_images.json')
OUTPUT = os.path.join(ROOT, 'src', 'historyImages.ts')
ASSETS = os.path.join(ROOT, 'src', 'assets', 'history')
PHOTO_MANIFEST = os.path.abspath(os.path.join(ROOT, '..', '..', 'assets', 'on-this-day', 'v1', 'manifest.json'))
CONFIG = os.path.join(ROOT, 'quick_settings', 'history_streaming.json')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--commit', help='Immutable published Git commit for the photo set')
    args = parser.parse_args()
    with open(CONFIG, encoding='utf-8') as handle:
        config = json.load(handle)
    commit = args.commit or config['commit']
    if not re.fullmatch(r'[0-9a-f]{40}', commit):
        raise SystemExit('A full immutable Git commit is required')
    with open(PHOTO_MANIFEST, encoding='utf-8-sig') as handle:
        photos = json.load(handle)['files']
    with open(MANIFEST, encoding='utf-8-sig') as handle:
        manifest = json.load(handle)

    order, index = [], {}
    for entries in manifest.values():
        for entry in entries:
            name = entry['file']
            if name not in index:
                index[name] = len(order)
                order.append(name)

    missing = [name for name in order if not os.path.isfile(os.path.join(ASSETS, name))]
    if missing:
        raise SystemExit('manifest references files that are not on disk: ' + ', '.join(missing))

    covers = {entry['file'] for entries in manifest.values() for entry in entries if entry.get('kind') == 'cover'}
    if covers.intersection(photos):
        raise SystemExit('Cover assets must not be streamed')
    if set(order) - covers - set(photos):
        raise SystemExit('Photos are missing from the published manifest')
    for name in set(order) - covers:
        with open(os.path.join(ASSETS, name), 'rb') as handle:
            data = handle.read()
        if len(data) != photos[name]['bytes'] or hashlib.sha256(data).hexdigest() != photos[name]['sha256']:
            raise SystemExit('Photo differs from the published manifest: ' + name)
    base = f'https://raw.githubusercontent.com/LoZazaMastro/Playhub/{commit}/assets/on-this-day/v1/'
    lines = [f"import img{position} from './assets/history/{name}';"
             for position, name in enumerate(order) if name in covers]
    for position, name in enumerate(order):
        if name not in covers:
            lines.append(f'const img{position} = ' + json.dumps(base + quote(name)) + ';')
    lines.append('')
    lines.append('/** Generated by tools/build-history-images.py — edit history_images.json instead. */')

    def record(entry):
        fields = ['file:' + json.dumps(entry['file']), f'url:img{index[entry["file"]]}',
                  'subject:' + json.dumps(entry.get('subject', ''), ensure_ascii=False)]
        if entry.get('kind'):
            fields.append('kind:' + json.dumps(entry['kind'], ensure_ascii=False))
        if entry.get('credit'):
            fields.append('credit:' + json.dumps(entry['credit'], ensure_ascii=False))
        return '{' + ','.join(fields) + '}'

    themes = ','.join(
        json.dumps(theme, ensure_ascii=False) + ':[' + ','.join(record(e) for e in entries) + ']'
        for theme, entries in manifest.items())
    lines.append('export const historyImages:Record<string,{file:string;url:string;subject:string;kind?:string;credit?:string}[]>={'
                 + themes + '};')
    integrity = {base + quote(name): {'sha256': photos[name]['sha256'], 'bytes': photos[name]['bytes']}
                 for name in order if name not in covers}
    lines.append('export const historyPhotoIntegrity:Record<string,{sha256:string;bytes:number}>=' + json.dumps(integrity, separators=(',', ':')) + ';')

    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(lines) + '\n')
    print(f'{OUTPUT}: {len(covers)} bundled covers, {len(integrity)} streamed photos, '
          f'{sum(len(v) for v in manifest.values())} entries, {len(manifest)} themes.')


if __name__ == '__main__':
    main()
