#!/usr/bin/env python3
"""Generate src/historyImages.ts from quick_settings/history_images.json.

The manifest is the single source of truth: this writes the bundler imports so a
file referenced by two themes is imported once, and the emitted order matches the
manifest so diffs stay readable.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, 'quick_settings', 'history_images.json')
OUTPUT = os.path.join(ROOT, 'src', 'historyImages.ts')
ASSETS = os.path.join(ROOT, 'src', 'assets', 'history')


def main():
    with open(MANIFEST, encoding='utf-8-sig') as handle:
        manifest = json.load(handle)

    order, index = [], {}
    for entries in manifest.values():
        for entry in entries:
            name = entry['file']
            if name not in index:
                index[name] = len(order)
                order.append(name)

    missing = [name for name in order if not os.path.isfile(os.path.join(ASSETS, name))]
    if missing:
        raise SystemExit('manifest references files that are not on disk: ' + ', '.join(missing))

    lines = [f"import img{position} from './assets/history/{name}';"
             for position, name in enumerate(order)]
    lines.append('')
    lines.append('/** Generated by tools/build-history-images.py — edit history_images.json instead. */')

    def record(entry):
        fields = ['file:' + json.dumps(entry['file']), f'url:img{index[entry["file"]]}',
                  'subject:' + json.dumps(entry.get('subject', ''), ensure_ascii=False)]
        if entry.get('kind'):
            fields.append('kind:' + json.dumps(entry['kind'], ensure_ascii=False))
        if entry.get('credit'):
            fields.append('credit:' + json.dumps(entry['credit'], ensure_ascii=False))
        return '{' + ','.join(fields) + '}'

    themes = ','.join(
        json.dumps(theme, ensure_ascii=False) + ':[' + ','.join(record(e) for e in entries) + ']'
        for theme, entries in manifest.items())
    lines.append('export const historyImages:Record<string,{file:string;url:string;subject:string;kind?:string;credit?:string}[]>={'
                 + themes + '};')

    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(lines) + '\n')
    print(f'{OUTPUT}: {len(order)} distinct files, '
          f'{sum(len(v) for v in manifest.values())} entries, {len(manifest)} themes.')


if __name__ == '__main__':
    main()
