<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Playhub/Services/XboxSteamShortcut.cs" Link="XboxSteamShortcut.cs" />
    <Compile Include="../Playhub/Vendor/VDFParser/**/*.cs" Link="VDFParser/%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="../Playhub.GameSession/UwpShortcutArguments.cs" Link="UwpShortcutArguments.cs" />
  </ItemGroup>
</Project>
