const rows: Record<string, string[]> = {
  en: ["Controller", "Controller settings in Steam", "Test inputs", "Sticks and deadzones", "Gyroscope calibration", "Current game layout", "No connected controller reported by Steam", "Steam navigation unavailable", "Controller capabilities unavailable", "Not supported by this controller", "No running game", "Controller disconnected or changed", "Steam Input"],
  it: ["Controller", "Impostazioni controller in Steam", "Test degli input", "Stick e zone morte", "Calibrazione giroscopio", "Layout del gioco in esecuzione", "Steam non segnala controller collegati", "Navigazione Steam non disponibile", "Capacità del controller non disponibili", "Non supportato da questo controller", "Nessun gioco in esecuzione", "Controller scollegato o cambiato", "Steam Input"],
  de: ["Controller", "Controller-Einstellungen in Steam", "Eingaben testen", "Sticks und Totzonen", "Gyroskop kalibrieren", "Layout des laufenden Spiels", "Steam meldet keinen verbundenen Controller", "Steam-Navigation nicht verfügbar", "Controller-Funktionen unbekannt", "Von diesem Controller nicht unterstützt", "Kein Spiel läuft", "Controller getrennt oder gewechselt", "Steam Input"],
  es: ["Mando", "Ajustes del mando en Steam", "Probar entradas", "Sticks y zonas muertas", "Calibrar giroscopio", "Diseño del juego en ejecución", "Steam no detecta mandos conectados", "Navegación de Steam no disponible", "Capacidades del mando desconocidas", "No compatible con este mando", "Ningún juego en ejecución", "Mando desconectado o cambiado", "Steam Input"],
  fr: ["Manette", "Paramètres de la manette dans Steam", "Tester les entrées", "Sticks et zones mortes", "Calibrage du gyroscope", "Configuration du jeu en cours", "Steam ne signale aucune manette connectée", "Navigation Steam indisponible", "Capacités de la manette inconnues", "Non pris en charge par cette manette", "Aucun jeu en cours", "Manette déconnectée ou remplacée", "Steam Input"],
  pt: ["Controle", "Configurações do controle no Steam", "Testar entradas", "Analógicos e zonas mortas", "Calibrar giroscópio", "Layout do jogo em execução", "O Steam não detecta controles conectados", "Navegação do Steam indisponível", "Recursos do controle desconhecidos", "Não suportado por este controle", "Nenhum jogo em execução", "Controle desconectado ou alterado", "Steam Input"],
  ru: ["Контроллер", "Настройки контроллера в Steam", "Проверка ввода", "Стики и мёртвые зоны", "Калибровка гироскопа", "Раскладка запущенной игры", "Steam не обнаружил подключённых контроллеров", "Навигация Steam недоступна", "Возможности контроллера неизвестны", "Не поддерживается этим контроллером", "Нет запущенной игры", "Контроллер отключён или заменён", "Steam Input"],
  uk: ["Контролер", "Налаштування контролера в Steam", "Перевірка вводу", "Стіки та мертві зони", "Калібрування гіроскопа", "Розкладка запущеної гри", "Steam не виявив підключених контролерів", "Навігація Steam недоступна", "Можливості контролера невідомі", "Не підтримується цим контролером", "Немає запущеної гри", "Контролер відключено або змінено", "Steam Input"],
  zh: ["控制器", "Steam 控制器设置", "测试输入", "摇杆与死区", "陀螺仪校准", "正在运行游戏的布局", "Steam 未检测到已连接的控制器", "Steam 导航不可用", "控制器功能未知", "此控制器不支持", "没有正在运行的游戏", "控制器已断开或更换", "Steam Input"],
  ja: ["コントローラー", "Steamのコントローラー設定", "入力テスト", "スティックとデッドゾーン", "ジャイロの調整", "実行中のゲームのレイアウト", "Steamが接続済みコントローラーを検出していません", "Steamのナビゲーションを利用できません", "コントローラーの機能が不明です", "このコントローラーでは非対応です", "実行中のゲームはありません", "コントローラーが切断または変更されました", "Steam Input"],
  ko: ["컨트롤러", "Steam 컨트롤러 설정", "입력 테스트", "스틱 및 데드존", "자이로 보정", "실행 중인 게임 레이아웃", "Steam에서 연결된 컨트롤러를 찾지 못했습니다", "Steam 탐색을 사용할 수 없습니다", "컨트롤러 기능을 확인할 수 없습니다", "이 컨트롤러에서 지원하지 않습니다", "실행 중인 게임이 없습니다", "컨트롤러가 연결 해제되거나 변경되었습니다", "Steam Input"],
  hi: ["कंट्रोलर", "Steam में कंट्रोलर सेटिंग", "इनपुट जाँचें", "स्टिक और डेडज़ोन", "जाइरोस्कोप कैलिब्रेशन", "चल रहे गेम का लेआउट", "Steam को कोई जुड़ा कंट्रोलर नहीं मिला", "Steam नेविगेशन उपलब्ध नहीं है", "कंट्रोलर की क्षमताएँ अज्ञात हैं", "यह कंट्रोलर समर्थन नहीं करता", "कोई गेम नहीं चल रहा", "कंट्रोलर डिस्कनेक्ट या बदल गया है", "Steam Input"],
};
export function controllerSettingsLocale(locale: string) {
  const aliases: Record<string, string> = { english: "en", italian: "it", german: "de", spanish: "es", french: "fr", brazilian: "pt", portuguese: "pt", russian: "ru", ukrainian: "uk", schinese: "zh", tchinese: "zh", japanese: "ja", koreana: "ko", hindi: "hi" };
  const key = locale.toLowerCase().split(/[-_]/)[0];
  const r = rows[aliases[key] ?? key] ?? rows.en;
  return { controller: r[0], settings: r[1], test: r[2], sticks: r[3], gyro: r[4], layout: r[5], noController: r[6], nativeUnavailable: r[7], unknownCapabilities: r[8], unsupported: r[9], noGame: r[10], changed: r[11], ready: r[12] };
}

export function controllerProfileLocale(locale: string) {
  const italian = /^(it|italian)(-|_|$)/i.test(locale);
  // Other languages use explicit English fallback until the new strings are translated.
  return italian ? {
    title: "Profili Playhub", offline: "Solo profilo locale - input reale non attivo",
    profile: "Profilo", source: "Pulsante sorgente", target: "Destinazione", none: "Disattivato",
    left: "Zona morta sinistra", right: "Zona morta destra", preview: "Anteprima sintetica",
    saved: "Salvato localmente", empty: "Profilo predefinito non salvato", dirty: "Modifiche non salvate",
    invalid: "Profilo non valido", storageError: "Archivio locale non disponibile",
    save: "Salva profilo locale", reset: "Ripristina valori predefiniti", discard: "Annulla modifiche",
  } : {
    title: "Playhub profiles", offline: "Local profile only - live input inactive",
    profile: "Profile", source: "Source button", target: "Target", none: "Disabled",
    left: "Left deadzone", right: "Right deadzone", preview: "Synthetic preview",
    saved: "Saved locally", empty: "Unsaved default profile", dirty: "Unsaved changes",
    invalid: "Invalid profile", storageError: "Local storage unavailable",
    save: "Save local profile", reset: "Restore defaults", discard: "Discard changes",
  };
}

const panelRows: Record<string, string[]> = {
  en: ["Your controller", "Test and calibration", "Configuration", "Choose the device to configure.", "Detected by Steam", "Connect a controller to see its available settings.", "Check the response of buttons, sticks and motion.", "Adjust controls for your game or this device.", "Open this controller's settings in Steam.", "Check which buttons and axes respond in Steam's input test.", "Adjust stick centering and the area that ignores small movements.", "Calibrate motion input to correct unwanted drift.", "Edit button assignments for the game currently running.", "Open in Steam"],
  it: ["Il tuo controller", "Test e calibrazione", "Configurazione", "Scegli il dispositivo da configurare.", "Rilevato da Steam", "Collega un controller per vedere le impostazioni disponibili.", "Controlla la risposta di pulsanti, stick e movimento.", "Adatta i comandi al gioco o al dispositivo.", "Apri le impostazioni di questo controller in Steam.", "Verifica quali pulsanti e assi rispondono nel test di Steam.", "Regola il centro degli stick e la zona che ignora i piccoli movimenti.", "Calibra il movimento per correggere la deriva involontaria.", "Modifica l'assegnazione dei pulsanti per il gioco in esecuzione.", "Apri in Steam"],
  de: ["Dein Controller", "Test und Kalibrierung", "Konfiguration", "Wähle das Gerät, das du einstellen möchtest.", "Von Steam erkannt", "Verbinde einen Controller, um verfügbare Einstellungen zu sehen.", "Prüfe die Reaktion von Tasten, Sticks und Bewegung.", "Passe die Steuerung an dein Spiel oder Gerät an.", "Öffne die Einstellungen dieses Controllers in Steam.", "Prüfe im Steam-Eingabetest, welche Tasten und Achsen reagieren.", "Passe die Stickmitte und den Bereich an, der kleine Bewegungen ignoriert.", "Kalibriere die Bewegungseingabe gegen unbeabsichtigte Drift.", "Bearbeite die Tastenbelegung für das laufende Spiel.", "In Steam öffnen"],
  es: ["Tu mando", "Prueba y calibración", "Configuración", "Elige el dispositivo que quieres configurar.", "Detectado por Steam", "Conecta un mando para ver los ajustes disponibles.", "Comprueba la respuesta de botones, sticks y movimiento.", "Adapta los controles al juego o al dispositivo.", "Abre los ajustes de este mando en Steam.", "Comprueba qué botones y ejes responden en la prueba de Steam.", "Ajusta el centro de los sticks y la zona que ignora pequeños movimientos.", "Calibra el movimiento para corregir la deriva involuntaria.", "Edita la asignación de botones del juego en ejecución.", "Abrir en Steam"],
  fr: ["Votre manette", "Test et calibrage", "Configuration", "Choisissez le périphérique à configurer.", "Détectée par Steam", "Connectez une manette pour voir les réglages disponibles.", "Vérifiez la réponse des boutons, des sticks et des mouvements.", "Adaptez les commandes au jeu ou au périphérique.", "Ouvrez les paramètres de cette manette dans Steam.", "Vérifiez quels boutons et axes répondent au test de Steam.", "Réglez le centre des sticks et la zone qui ignore les petits mouvements.", "Calibrez les mouvements pour corriger une dérive involontaire.", "Modifiez l'affectation des boutons du jeu en cours.", "Ouvrir dans Steam"],
  pt: ["Seu controle", "Teste e calibração", "Configuração", "Escolha o dispositivo que deseja configurar.", "Detectado pelo Steam", "Conecte um controle para ver as configurações disponíveis.", "Confira a resposta dos botões, analógicos e movimentos.", "Adapte os comandos ao jogo ou ao dispositivo.", "Abra as configurações deste controle no Steam.", "Confira quais botões e eixos respondem no teste do Steam.", "Ajuste o centro dos analógicos e a zona que ignora pequenos movimentos.", "Calibre o movimento para corrigir desvios involuntários.", "Edite a atribuição dos botões do jogo em execução.", "Abrir no Steam"],
  ru: ["Ваш контроллер", "Проверка и калибровка", "Настройка", "Выберите устройство для настройки.", "Обнаружен Steam", "Подключите контроллер, чтобы увидеть доступные настройки.", "Проверьте отклик кнопок, стиков и движения.", "Настройте управление для игры или устройства.", "Откройте настройки этого контроллера в Steam.", "Проверьте реакцию кнопок и осей в тесте Steam.", "Настройте центр стиков и зону игнорирования мелких движений.", "Откалибруйте движение, чтобы устранить непроизвольный дрейф.", "Измените назначение кнопок для запущенной игры.", "Открыть в Steam"],
  uk: ["Ваш контролер", "Перевірка й калібрування", "Налаштування", "Виберіть пристрій для налаштування.", "Виявлено Steam", "Підключіть контролер, щоб побачити доступні налаштування.", "Перевірте реакцію кнопок, стіків і руху.", "Налаштуйте керування для гри або пристрою.", "Відкрийте налаштування цього контролера в Steam.", "Перевірте реакцію кнопок і осей у тесті Steam.", "Налаштуйте центр стіків і зону ігнорування дрібних рухів.", "Відкалібруйте рух, щоб усунути мимовільний дрейф.", "Змініть призначення кнопок для запущеної гри.", "Відкрити в Steam"],
  zh: ["你的控制器", "测试与校准", "配置", "选择要配置的设备。", "Steam 已检测到", "连接控制器以查看可用设置。", "检查按键、摇杆和动作的响应。", "为游戏或设备调整控制设置。", "在 Steam 中打开此控制器的设置。", "在 Steam 输入测试中检查按键和轴的响应。", "调整摇杆中心以及忽略微小移动的区域。", "校准动作输入以纠正意外漂移。", "编辑当前运行游戏的按键分配。", "在 Steam 中打开"],
  ja: ["使用するコントローラー", "テストと調整", "設定", "設定するデバイスを選択します。", "Steamが検出済み", "コントローラーを接続すると、利用可能な設定が表示されます。", "ボタン、スティック、動きの反応を確認します。", "ゲームやデバイスに合わせて操作を設定します。", "Steamでこのコントローラーの設定を開きます。", "Steamの入力テストでボタンや軸の反応を確認します。", "スティックの中心と小さな動きを無視する範囲を調整します。", "動きを調整して意図しないドリフトを補正します。", "実行中のゲームのボタン割り当てを編集します。", "Steamで開く"],
  ko: ["내 컨트롤러", "테스트 및 보정", "설정", "설정할 장치를 선택하세요.", "Steam에서 감지됨", "컨트롤러를 연결하면 사용 가능한 설정이 표시됩니다.", "버튼, 스틱 및 동작의 반응을 확인합니다.", "게임이나 장치에 맞게 조작을 설정합니다.", "Steam에서 이 컨트롤러의 설정을 엽니다.", "Steam 입력 테스트에서 버튼과 축의 반응을 확인합니다.", "스틱 중심과 작은 움직임을 무시하는 영역을 조정합니다.", "동작을 보정하여 의도하지 않은 드리프트를 수정합니다.", "실행 중인 게임의 버튼 할당을 편집합니다.", "Steam에서 열기"],
  hi: ["आपका कंट्रोलर", "परीक्षण और कैलिब्रेशन", "कॉन्फ़िगरेशन", "कॉन्फ़िगर करने के लिए डिवाइस चुनें।", "Steam ने पहचान लिया", "उपलब्ध सेटिंग देखने के लिए कंट्रोलर जोड़ें।", "बटन, स्टिक और गति की प्रतिक्रिया जाँचें।", "गेम या डिवाइस के लिए नियंत्रण समायोजित करें।", "Steam में इस कंट्रोलर की सेटिंग खोलें।", "Steam इनपुट परीक्षण में बटन और अक्षों की प्रतिक्रिया जाँचें।", "स्टिक का केंद्र और छोटी गति को अनदेखा करने वाला क्षेत्र समायोजित करें।", "अनचाहा विचलन सुधारने के लिए गति का कैलिब्रेशन करें।", "चल रहे गेम के बटन असाइनमेंट बदलें।", "Steam में खोलें"],
};
export function controllerPanelLocale(locale: string) {
  const aliases: Record<string, string> = { english: "en", italian: "it", german: "de", spanish: "es", latam: "es", french: "fr", brazilian: "pt", portuguese: "pt", russian: "ru", ukrainian: "uk", schinese: "zh", tchinese: "zh", japanese: "ja", koreana: "ko", hindi: "hi" };
  const key = locale.toLowerCase().split(/[-_]/)[0];
  const r = panelRows[aliases[key] ?? key] ?? panelRows.en;
  return { device: r[0], input: r[1], configure: r[2], deviceHint: r[3], connected: r[4], emptyHint: r[5], inputHint: r[6], configHint: r[7], settings: r[8], test: r[9], sticks: r[10], gyro: r[11], layout: r[12], open: r[13] };
}
