const rows: Record<string, string[]> = {
  en: ["Lighting", "Device", "Brightness", "Apply color", "Turn off", "No compatible lighting device detected", "Lighting controls are not available for this device", "Apply this lighting change?", "Experimental Windows support. This may replace the device's first lighting profile. The previous state cannot be restored automatically.", "Command sent; device appearance has not been verified", "Could not apply the lighting change"],
  it: ["Illuminazione", "Dispositivo", "Luminosità", "Applica colore", "Spegni", "Nessun dispositivo di illuminazione compatibile rilevato", "Controlli di illuminazione non disponibili per questo dispositivo", "Applicare questa modifica all'illuminazione?", "Supporto Windows sperimentale. La modifica potrebbe sostituire il primo profilo di illuminazione del dispositivo. Lo stato precedente non può essere ripristinato automaticamente.", "Comando inviato; risultato sul dispositivo non verificato", "Impossibile applicare la modifica all'illuminazione"],
  de: ["Beleuchtung", "Gerät", "Helligkeit", "Farbe anwenden", "Ausschalten", "Kein kompatibles Beleuchtungsgerät erkannt", "Beleuchtungssteuerung für dieses Gerät nicht verfügbar", "Diese Beleuchtungsänderung anwenden?", "Experimentelle Windows-Unterstützung. Das erste Beleuchtungsprofil des Geräts kann ersetzt werden. Der vorherige Zustand lässt sich nicht automatisch wiederherstellen.", "Befehl gesendet; Darstellung am Gerät nicht überprüft", "Beleuchtungsänderung konnte nicht angewendet werden"],
  es: ["Iluminación", "Dispositivo", "Brillo", "Aplicar color", "Apagar", "No se detectó ningún dispositivo de iluminación compatible", "Los controles de iluminación no están disponibles para este dispositivo", "¿Aplicar este cambio de iluminación?", "Compatibilidad experimental con Windows. Puede reemplazar el primer perfil de iluminación del dispositivo. El estado anterior no se puede restaurar automáticamente.", "Comando enviado; aspecto del dispositivo sin verificar", "No se pudo aplicar el cambio de iluminación"],
  fr: ["Éclairage", "Appareil", "Luminosité", "Appliquer la couleur", "Éteindre", "Aucun appareil d'éclairage compatible détecté", "Commandes d'éclairage indisponibles pour cet appareil", "Appliquer cette modification d'éclairage ?", "Prise en charge Windows expérimentale. Le premier profil d'éclairage de l'appareil peut être remplacé. L'état précédent ne peut pas être restauré automatiquement.", "Commande envoyée ; résultat sur l'appareil non vérifié", "Impossible d'appliquer la modification d'éclairage"],
  pt: ["Iluminação", "Dispositivo", "Brilho", "Aplicar cor", "Desligar", "Nenhum dispositivo de iluminação compatível detectado", "Controles de iluminação indisponíveis para este dispositivo", "Aplicar esta alteração de iluminação?", "Suporte experimental ao Windows. Pode substituir o primeiro perfil de iluminação do dispositivo. O estado anterior não pode ser restaurado automaticamente.", "Comando enviado; resultado no dispositivo não verificado", "Não foi possível aplicar a alteração de iluminação"],
  ru: ["Подсветка", "Устройство", "Яркость", "Применить цвет", "Выключить", "Совместимое устройство подсветки не обнаружено", "Управление подсветкой этого устройства недоступно", "Применить изменение подсветки?", "Экспериментальная поддержка Windows. Первый профиль подсветки устройства может быть заменён. Автоматически восстановить прежнее состояние невозможно.", "Команда отправлена; результат на устройстве не проверен", "Не удалось изменить подсветку"],
  uk: ["Підсвічування", "Пристрій", "Яскравість", "Застосувати колір", "Вимкнути", "Сумісний пристрій підсвічування не виявлено", "Керування підсвічуванням цього пристрою недоступне", "Застосувати зміну підсвічування?", "Експериментальна підтримка Windows. Перший профіль підсвічування пристрою може бути замінено. Автоматично відновити попередній стан неможливо.", "Команду надіслано; результат на пристрої не перевірено", "Не вдалося змінити підсвічування"],
  zh: ["灯光", "设备", "亮度", "应用颜色", "关闭", "未检测到兼容的灯光设备", "此设备暂不支持灯光控制", "应用此灯光更改？", "Windows 实验性支持。此操作可能覆盖设备的第一个灯光配置，无法自动恢复之前的状态。", "命令已发送；尚未验证设备显示效果", "无法应用灯光更改"],
  ja: ["ライティング", "デバイス", "明るさ", "色を適用", "消灯", "対応するライティングデバイスが見つかりません", "このデバイスのライティング制御は利用できません", "このライティング変更を適用しますか？", "Windowsへの試験的な対応です。デバイスの最初のライティングプロファイルが上書きされる可能性があります。以前の状態を自動で復元することはできません。", "コマンド送信済み。デバイスの表示結果は未確認です", "ライティング変更を適用できませんでした"],
  ko: ["조명", "기기", "밝기", "색상 적용", "끄기", "호환되는 조명 기기가 감지되지 않았습니다", "이 기기의 조명 제어를 사용할 수 없습니다", "이 조명 변경을 적용할까요?", "실험적인 Windows 지원입니다. 기기의 첫 번째 조명 프로필이 덮어써질 수 있습니다. 이전 상태는 자동으로 복원할 수 없습니다.", "명령 전송 완료. 기기의 표시 결과는 확인되지 않았습니다", "조명 변경을 적용하지 못했습니다"],
  hi: ["लाइटिंग", "डिवाइस", "चमक", "रंग लागू करें", "बंद करें", "कोई संगत लाइटिंग डिवाइस नहीं मिला", "इस डिवाइस के लिए लाइटिंग नियंत्रण उपलब्ध नहीं हैं", "यह लाइटिंग बदलाव लागू करें?", "प्रायोगिक Windows समर्थन। यह डिवाइस की पहली लाइटिंग प्रोफ़ाइल को बदल सकता है। पिछली स्थिति अपने आप बहाल नहीं की जा सकती।", "कमांड भेजी गई; डिवाइस पर परिणाम सत्यापित नहीं है", "लाइटिंग बदलाव लागू नहीं हो सका"],
};
export function rgbLocale(locale: string) {
  const row = rows[locale.split("-")[0]] ?? rows.en;
  return { title: row[0], device: row[1], brightness: row[2], apply: row[3], off: row[4], empty: row[5], unavailable: row[6], confirm: row[7], warning: row[8], sent: row[9], error: row[10] };
}
